export const colors = {
  whiteWords: "white",
  redWords: "red",
  greyWords: "grey",
  goldWords: "gold",
  appName: "darkblue",
  loginButton: "#87CBB9",
  pressedLoginButton: "#B9EDDD",
  inputBackground: "#FFF6E0",
  redButton: "darkred",
  pressedRedButton: "red",
  blueButton: "#1e90ff",
  cardBackground: "#a9a9a9",
  shadowColor: "#000",
  gradient1: "#F7D060",
  gradient2: "#F3E99F",
  gradient3: "#98D8AA",
  topheader: "#FFDD83",
  bottomheader: "#98D8AA",
  tabBarPressed: "#557A46",
  tabBarNotPressed: `grey`,
};
